name: Test Pipeline

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  DAY_OF_WEEK: Monday

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      SELAMLAMA: Hello
    steps:
      - name: Checkout Adimi
        uses: actions/checkout@v4
      - name: Docker Login
        uses: docker/login-action@v3.0.0
        with:
          # Username used to log against the Docker registry
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          # Password or personal access token used to log against the Docker registry
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - shell: bash
        env:
          SUPER_SECRET: ${{ secrets.DOCKERHUB_USERNAME }}
        run: |
          echo "$SUPER_SECRET"
