name: Test Pipeline

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  DAY_OF_WEEK: Monday

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      SELAMLAMA: Hello
    steps:
      - id: checkout
        uses: actions/checkout@v4
        
      - name: Generate 0 or 1
        id: generate_number
        run: echo "random_number=$(($RANDOM % 2))" >> $GITHUB_OUTPUT
      
      - name: Pass or fail
        run: |
          echo ${{ steps.generate_number.outputs }}
