name: Test Pipeline

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  DAY_OF_WEEK: Monday

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      SELAMLAMA: Hello
    steps:
      - name: Checkout Adimi
        uses: actions/checkout@v4
      - shell: bash
        run: |
          expr 1 + 1 > output.log
      - name: Upload output file
        uses: actions/upload-artifact@v3
        with:
          name: output-log-file
          path: output.log
  test2:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Echo
        run: echo output.log
